CREATE SCHEMA IF NOT EXISTS labeler;

CREATE TABLE IF NOT EXISTS labeler.responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id TEXT NOT NULL,
    tweet_id INTEGER NOT NULL,
    label TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (participant_id, tweet_id)
);

-- Flask accesses this private schema through PostgreSQL, not the public Data API.
REVOKE ALL ON SCHEMA labeler FROM PUBLIC;
REVOKE ALL ON labeler.responses FROM PUBLIC;
